import React, { useState, useRef } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Animated,
  Dimensions,
} from 'react-native';
import { BlurView } from 'expo-blur';
import { FontAwesome5 } from '@expo/vector-icons';
import { useTheme } from '../../contexts/ThemeContext';

const { height } = Dimensions.get('window');

interface PrivacyPolicyProps {
  onAccept: (accepted: boolean) => void;
  accepted: boolean;
}

export const PrivacyPolicy: React.FC<PrivacyPolicyProps> = ({
  onAccept,
  accepted
}) => {
  const { isDarkMode } = useTheme();
  const [hasScrolledToBottom, setHasScrolledToBottom] = useState(false);
  const checkboxScaleAnim = useRef(new Animated.Value(1)).current;
  const scrollViewRef = useRef<ScrollView>(null);

  const handleScroll = (event: any) => {
    const { layoutMeasurement, contentOffset, contentSize } = event.nativeEvent;
    const paddingToBottom = 20;
    
    if (layoutMeasurement.height + contentOffset.y >= contentSize.height - paddingToBottom) {
      setHasScrolledToBottom(true);
    }
  };

  const handleAcceptToggle = () => {
    Animated.sequence([
      Animated.timing(checkboxScaleAnim, {
        toValue: 0.9,
        duration: 100,
        useNativeDriver: true,
      }),
      Animated.timing(checkboxScaleAnim, {
        toValue: 1,
        duration: 100,
        useNativeDriver: true,
      }),
    ]).start();

    onAccept(!accepted);
  };

  const privacyContent = `NUMINA AI - PRIVACY POLICY

Effective Date: July 19, 2025

This Privacy Policy describes how Numina LLC ("Numina AI," "we," "us," or "our") collects, uses, stores, shares, and protects your information when you use our mobile application, web application, associated backend APIs, AI models, tools, features, and content (collectively, the "Service").

By accessing or using the Service, you agree to the collection and use of information in accordance with this Privacy Policy. Please read this Privacy Policy carefully.

1. Definitions

Service: Refers to the Numina AI mobile application, web application, and any associated backend APIs, AI models, tools, features, and content provided by Numina AI.

User ("You," "Your"): Refers to any individual or entity accessing or using the Service.

Account: Refers to the user account created to access and use the Service.

Personal Data: Any information that relates to an identified or identifiable individual.

Usage Data: Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g., the duration of a page visit).

Content: Refers to any data, text, images, audio, video, or other materials that you upload, submit, or transmit through the Service, or that is generated by the Service in response to your input.

SynthUBPM (Synthetic User Behavior Profile Model): Numina AI's proprietary advanced system for understanding your behavior patterns, communication styles, emotional responses, and temporal interactions.

2. Information We Collect

We collect various types of information for various purposes to provide and improve our Service to you.

2.1. Information You Provide Directly:
• Account Information: When you create an Account, we collect your display name, email address, password (hashed), and any optional profile information you provide, such as your bio and location.
• Content You Create: This includes all your interactions with the AI, such as text inputs, uploaded images, audio (if voice input is used), and any other data you submit. This also includes journal entries, mood logs, and any explicit feedback you provide.
• Payment Information: If you subscribe to a premium tier or purchase credits, we collect necessary payment information (e.g., credit card details, billing address) which is processed by our third-party payment processor (Stripe). We do not store full credit card numbers on our servers.

2.2. Information Collected Automatically (Usage Data & Behavioral Data):
• Interaction Data: We collect data about how you use the Service, including chat session duration, frequency of interactions, features used, tools invoked (e.g., web search, calculator, code generator), types of queries, and responses received.
• Behavioral Patterns (SynthUBPM Data): Our proprietary SynthUBPM analyzes your interaction data to identify patterns related to your communication style (e.g., detailed, brief, inquisitive, task-oriented), emotional responses (e.g., emotional variance, stress response patterns), temporal activity (e.g., peak hours), and decision-making approaches. This data is used to build and refine your personalized SynthUBPM.
• Emotional Analytics Data: We collect data on your reported emotional states (e.g., mood logs, intensity) and analyze emotional cues within your conversations to track your emotional journey and provide insights.
• Device Information: We may collect information about the device you use to access the Service, such as device type, operating system, unique device identifiers, and mobile network information.
• Log Data: Our servers automatically record information that your browser or mobile application sends whenever you visit our Service. This may include your IP address, browser type, referring/exit pages, and timestamps.
• Location Information: If you enable location services, we may collect general location data (e.g., city-level) to provide location-based features like event matching.

3. How We Use Your Information

We use the collected information for various purposes, including:

• To Provide and Maintain the Service: Operating, maintaining, and improving the core functionality of Numina AI.
• Personalization: To adapt the AI's personality, communication style, and responses to your unique behavioral patterns (SynthUBPM), emotional state, and preferences, making interactions more personalized and meaningful.
• Self-Discovery & Insights: To generate personalized analytics, insights, and recommendations related to your communication, emotional well-being, growth trajectory, and behavioral patterns.
• Content Generation: To generate text, code, images, or other content in response to your prompts and requests.
• Tool Execution: To execute specialized AI tools (e.g., web search, calculator, code generator) to fulfill your requests.
• Emotional Support: To provide empathetic responses and supportive guidance based on your emotional state and needs.
• Social Matching: To connect you with like-minded individuals or events (via the "Cloud" section) based on your interests, location, and emotional compatibility (using anonymized or aggregated data where appropriate).
• Account Management: To manage your Account, process transactions (subscriptions, credits), and provide customer support.
• Communication: To send you notifications, updates, security alerts, and administrative messages.
• Analytics and Research: To monitor and analyze usage and trends, improve the Service's performance, optimize features, and develop new capabilities. This includes analyzing aggregated and anonymized behavioral patterns for collective insights.
• Security and Fraud Prevention: To detect, prevent, and address technical issues, fraud, and other illegal activities.
• Compliance: To comply with legal obligations and enforce our Terms of Service.

4. How We Share Your Information

We do not sell your Personal Data. We may share your information in the following situations:

• With Service Providers: We may share your information with third-party vendors and service providers who perform services on our behalf, such as hosting, payment processing (Stripe), email delivery, and analytics. These providers are obligated to protect your information and use it only for the purposes for which it was disclosed.
• With AI Model Providers (e.g., OpenRouter): Your chat inputs and context (excluding directly identifiable Personal Data unless necessary for the core service) are sent to third-party AI model providers (like OpenAI via OpenRouter) to generate responses. We employ strategies to minimize data sent and optimize costs.
• For Collective Intelligence: We may aggregate and anonymize your behavioral patterns, emotional insights, and other usage data to generate collective insights and trends. This aggregated, anonymized data may be shared with the broader Numina community or used for research and product development, without identifying any individual user.
• With Your Consent: We may disclose your Personal Data for any other purpose with your explicit consent.
• Business Transfers: In connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business by another company.
• Legal Requirements: When required to do so by law or in response to valid requests by public authorities (e.g., a court order or government agency).
• To Protect Our Rights: To protect and defend the rights or property of Numina AI, including enforcing our Terms of Service.

5. Data Security

We are committed to protecting the security of your information. We implement robust technical and organizational measures designed to safeguard your data against unauthorized access, alteration, disclosure, or destruction. These measures include:

• Encryption: All data transmitted between your device and our servers is encrypted using HTTPS (SSL/TLS). Sensitive data at rest is stored securely in our MongoDB database.
• Authentication: We use secure token-based authentication (JWT) for user access.
• Access Control: Strict access controls and role-based permissions are in place to limit who can access your data internally.
• Input Sanitization: All user inputs are rigorously sanitized to prevent injection attacks.
• Rate Limiting: APIs are protected with rate limiters to prevent abuse and denial-of-service attacks.
• Security Headers: Implementation of security headers (e.g., Helmet.js) to enhance protection against common web vulnerabilities.
• SSL Pinning (Mobile): For enhanced mobile security, we implement SSL pinning to prevent man-in-the-middle attacks.
• Regular Security Audits: We conduct internal security reviews and strive to follow industry best practices.

While we strive to use commercially acceptable means to protect your Personal Data, no method of transmission over the Internet or method of electronic storage is 100% secure. Therefore, we cannot guarantee its absolute security.

6. Data Retention

We retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy, unless a longer retention period is required or permitted by law (such as tax, accounting, or other legal requirements).

When we have no ongoing legitimate business need to process your Personal Data, we will either delete or anonymize it, or, if this is not possible (for example, because your Personal Data has been stored in backup archives), then we will securely store your Personal Data and isolate it from any further processing until deletion is possible.

7. Your Data Protection Rights

You have certain rights regarding your Personal Data, subject to applicable law:

• Right to Access: You have the right to request access to the Personal Data we hold about you.
• Right to Rectification: You have the right to request that we correct any inaccurate or incomplete Personal Data.
• Right to Erasure ("Right to Be Forgotten"): You have the right to request the deletion of your Personal Data from our systems. Please note that deleting your data will effectively reset your SynthUBPM and associated personalized experiences.
• Right to Restrict Processing: You have the right to request that we restrict the processing of your Personal Data under certain conditions.
• Right to Data Portability: You have the right to receive your Personal Data in a structured, commonly used, and machine-readable format.
• Right to Object: You have the right to object to our processing of your Personal Data under certain conditions.
• Withdraw Consent: Where we rely on your consent to process your Personal Data, you have the right to withdraw that consent at any time.

To exercise any of these rights, please contact us using the contact information provided below. We will respond to your request in accordance with applicable data protection laws.

8. Children's Privacy

Our Service is not intended for use by individuals under the age of 13. We do not knowingly collect Personal Data from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.

9. Changes to This Privacy Policy

We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Effective Date" at the top. We will also inform you via email and/or a prominent notice on our Service prior to the change becoming effective. You are advised to review this Privacy Policy periodically for any changes.

10. Contact Us

If you have any questions about this Privacy Policy, your data, or our practices, please contact us:

By email: numinaworks@gmail.com

Disclaimer: This Privacy Policy is a comprehensive draft based on the information provided about Numina AI's functionalities and data handling. It is intended as a starting point and must be reviewed, adapted, and approved by a qualified legal professional to ensure full compliance with all applicable laws and regulations in relevant jurisdictions (e.g., GDPR, CCPA, etc.). Numina AI is not providing legal advice.`;

  return (
    <View style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={[
          styles.headerText,
          { color: isDarkMode ? '#ffffff' : '#000000' }
        ]}>
          Privacy Policy
        </Text>
        <Text style={[
          styles.subHeaderText,
          { color: isDarkMode ? '#888888' : '#666666' }
        ]}>
          Please read and accept our privacy policy to continue
        </Text>
      </View>

      {/* Scrollable Privacy Content */}
      <View style={[
        styles.privacyContainer,
        {
          backgroundColor: isDarkMode ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.02)',
          borderColor: isDarkMode ? '#333333' : '#e0e0e0',
        }
      ]}>
        <ScrollView
          ref={scrollViewRef}
          style={styles.scrollView}
          contentContainerStyle={styles.scrollContent}
          onScroll={handleScroll}
          scrollEventThrottle={16}
          showsVerticalScrollIndicator={true}
        >
          <Text style={[
            styles.privacyText,
            { color: isDarkMode ? '#cccccc' : '#444444' }
          ]}>
            {privacyContent}
          </Text>
        </ScrollView>
        
        {/* Scroll indicator */}
        {!hasScrolledToBottom && (
          <TouchableOpacity 
            style={styles.scrollIndicator}
            onPress={() => {
              scrollViewRef.current?.scrollToEnd({ animated: true });
            }}
            activeOpacity={0.8}
          >
            <BlurView 
              intensity={20} 
              tint={isDarkMode ? 'dark' : 'light'}
              style={styles.blurOverlay}
            />
            <View style={styles.scrollIndicatorContent}>
              <FontAwesome5 
                name="chevron-down" 
                size={16} 
                color={isDarkMode ? '#ffffff' : '#000000'} 
              />
              <Text style={[
                styles.scrollIndicatorText,
                { color: isDarkMode ? '#ffffff' : '#000000' }
              ]}>
                Tap to scroll to bottom
              </Text>
            </View>
          </TouchableOpacity>
        )}
      </View>

      {/* Acceptance Checkbox */}
      <View style={styles.checkboxContainer}>
        <Animated.View style={{ transform: [{ scale: checkboxScaleAnim }] }}>
          <TouchableOpacity
            style={[
              styles.checkbox,
              {
                backgroundColor: accepted 
                  ? (isDarkMode ? '#add5fa' : '#007AFF')
                  : 'transparent',
                borderColor: accepted 
                  ? (isDarkMode ? '#add5fa' : '#007AFF')
                  : (isDarkMode ? '#666666' : '#cccccc'),
              }
            ]}
            onPress={handleAcceptToggle}
            disabled={!hasScrolledToBottom}
          >
            {accepted && (
              <FontAwesome5 
                name="check" 
                size={12} 
                color={isDarkMode ? '#000000' : '#ffffff'} 
              />
            )}
          </TouchableOpacity>
        </Animated.View>
        
        <TouchableOpacity 
          style={styles.checkboxTextContainer}
          onPress={handleAcceptToggle}
          disabled={!hasScrolledToBottom}
        >
          <Text style={[
            styles.checkboxText,
            { 
              color: hasScrolledToBottom 
                ? (isDarkMode ? '#ffffff' : '#000000')
                : (isDarkMode ? '#666666' : '#999999')
            }
          ]}>
            I have read and agree to the Privacy Policy
          </Text>
        </TouchableOpacity>
      </View>

      {/* Status indicator */}
      {!hasScrolledToBottom && (
        <Text style={[
          styles.statusText,
          { color: isDarkMode ? '#888888' : '#666666' }
        ]}>
          Please scroll through the entire document to continue
        </Text>
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  header: {
    marginBottom: 20,
    alignItems: 'center',
  },
  headerText: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 4,
    fontFamily: 'System',
  },
  subHeaderText: {
    fontSize: 14,
    fontWeight: '400',
    textAlign: 'center',
    fontFamily: 'System',
  },
  privacyContainer: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    position: 'relative',
    marginBottom: 20,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  privacyText: {
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '400',
    fontFamily: 'System',
  },
  scrollIndicator: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    overflow: 'hidden',
  },
  blurOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  scrollIndicatorContent: {
    padding: 12,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  scrollIndicatorText: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'System',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    gap: 12,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxTextContainer: {
    flexShrink: 1,
  },
  checkboxText: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'System',
    textAlign: 'center',
  },
  statusText: {
    fontSize: 12,
    fontWeight: '400',
    textAlign: 'center',
    fontFamily: 'System',
  },
});