import React, { useState, useRef } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Animated,
  Dimensions,
} from 'react-native';
import { BlurView } from 'expo-blur';
import { FontAwesome5 } from '@expo/vector-icons';
import { useTheme } from '../../contexts/ThemeContext';

const { height } = Dimensions.get('window');

interface TermsOfServiceProps {
  onAccept: (accepted: boolean) => void;
  accepted: boolean;
}

export const TermsOfService: React.FC<TermsOfServiceProps> = ({
  onAccept,
  accepted
}) => {
  const { isDarkMode } = useTheme();
  const [hasScrolledToBottom, setHasScrolledToBottom] = useState(false);
  const checkboxScaleAnim = useRef(new Animated.Value(1)).current;
  const scrollViewRef = useRef<ScrollView>(null);

  const handleScroll = (event: any) => {
    const { layoutMeasurement, contentOffset, contentSize } = event.nativeEvent;
    const paddingToBottom = 20;
    
    if (layoutMeasurement.height + contentOffset.y >= contentSize.height - paddingToBottom) {
      setHasScrolledToBottom(true);
    }
  };

  const handleAcceptToggle = () => {
    // Checkbox animation
    Animated.sequence([
      Animated.timing(checkboxScaleAnim, {
        toValue: 0.9,
        duration: 100,
        useNativeDriver: true,
      }),
      Animated.timing(checkboxScaleAnim, {
        toValue: 1,
        duration: 100,
        useNativeDriver: true,
      }),
    ]).start();

    onAccept(!accepted);
  };

  const termsContent = `NUMINA AI - TERMS OF SERVICE

Effective Date: July 18, 2025

Welcome to Numina AI! These Terms of Service ("Terms") govern your access to and use of the Numina AI mobile application, web application, and related services (collectively, the "Service"), provided by Numina LLC ("Numina AI," "we," "us," or "our").

By accessing or using the Service, you agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, you may not access or use the Service.

1. Definitions

"Service" refers to the Numina AI mobile application, web application, and any associated backend APIs, AI models, tools, features, and content provided by Numina AI.

"User," "You," "Your" refers to any individual or entity accessing or using the Service.

"Account" refers to the user account created to access and use the Service.

"Content" refers to any data, text, images, audio, video, or other materials that you upload, submit, or transmit through the Service, or that is generated by the Service in response to your input.

"SynthUBPM" refers to Synthetic User Behavior Pattern Modeling, an advanced analytics system within the Service designed to understand and predict user behavior.

"AI Tools" refers to the specialized functionalities within the Service (e.g., web search, calculator, code generator) that can be invoked by the AI.

"Collective Data" refers to anonymized and aggregated user data used to derive collective insights, as further detailed in our Privacy Policy.

2. Acceptance of Terms

By creating an Account, clicking "I Agree," or otherwise accessing or using any part of the Service, you acknowledge that you have read, understood, and agree to be bound by these Terms, as well as our Privacy Policy. If you are using the Service on behalf of an organization, you are agreeing to these Terms for that organization and warrant that you have the authority to bind that organization to these Terms.

3. Changes to Terms

We reserve the right to modify or update these Terms at any time, in our sole discretion. We will notify you of any material changes by posting the new Terms on our website or through the Service, and updating the "Effective Date" at the top of these Terms. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms. If you do not agree to the new Terms, you must stop using the Service.

4. Access and Accounts

4.1. Eligibility: You must be at least 18 years old to create an Account and use the Service. By using the Service, you represent and warrant that you meet this age requirement.

4.2. Account Creation: To access certain features of the Service, you may be required to create an Account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete.

4.3. Account Security: You are solely responsible for maintaining the confidentiality of your Account credentials (username, password, etc.) and for all activities that occur under your Account. You agree to notify us immediately of any unauthorized use of your Account or any other breach of security. We will not be liable for any loss or damage arising from your failure to comply with this section.

5. Description of Service

Numina AI provides an advanced AI companion service designed to enhance your productivity, provide insights, and offer personalized assistance. Key features of the Service include:

AI Chat & Completions: Interactive AI conversations and text generation.

AI Tools: Access to a suite of specialized AI tools (e.g., web search, calculator, code generator, weather check, academic search, image search, etc.) for various tasks.

Personalization Engine: The AI adapts its personality and responses based on your interactions and behavioral patterns.

Synthetic User Behavior Pattern Modeling (SynthUBPM): Advanced analytics to identify and predict your behavioral patterns, emotional states (e.g., "excited" detection), and provide behavioral insights and notifications.

Emotional Analytics: Tracking and analysis of user emotions to provide deep insights.

Collective Intelligence: Anonymized and aggregated insights derived from collective user patterns (with your consent, as per our Privacy Policy).

Real-time Features: Live updates and interactions via WebSocket connections.

Offline Synchronization: A queue system for mobile functionality, allowing you to use certain features offline with data syncing when connection is restored.

File Upload: Support for uploading and processing various file types, including images, text files, and PDFs.

Subscription & Credit System: Access to premium features and usage tracking via subscriptions and/or credits.

6. User Responsibilities and Conduct

6.1. Permitted Use: You agree to use the Service only for lawful purposes and in accordance with these Terms.

6.2. Prohibited Conduct: You agree not to:
* Use the Service for any illegal, harmful, or fraudulent purpose.
* Transmit any Content that is unlawful, defamatory, obscene, pornographic, hateful, or discriminatory.
* Infringe upon the intellectual property rights of others.
* Attempt to gain unauthorized access to the Service, other Accounts, or computer systems or networks connected to the Service.
* Interfere with or disrupt the integrity or performance of the Service or data contained therein.
* Upload or transmit viruses, worms, or any other malicious code.
* Engage in any activity that could disable, overburden, or impair the proper working of the Service.
* Use the Service to generate or disseminate misinformation, hate speech, or content that promotes violence or illegal activities.
* Reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code or underlying algorithms of the Service.
* Scrape, crawl, or use any automated means to access or collect data from the Service without our express written permission.

6.3. Content Standards: Any Content you provide or generate through the Service must comply with applicable laws and these Terms. You are solely responsible for your Content.

7. Intellectual Property

7.1. Our Intellectual Property: All rights, title, and interest in and to the Service, including all software, text, graphics, logos, trademarks, and other intellectual property, are and will remain the exclusive property of Numina AI and its licensors. These Terms do not grant you any right to use any of our trademarks, logos, domain names, or other brand features.

7.2. Your Content: You retain ownership of any Content you submit to the Service. By submitting Content, you grant Numina AI a worldwide, non-exclusive, royalty-free, transferable, and sublicensable license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, publicly perform, and display your Content in connection with the operation and improvement of the Service, subject to our Privacy Policy.

7.3. AI-Generated Content: Content generated by the AI based on your input may be used by you for your personal or commercial purposes, provided such use complies with these Terms and applicable laws. Numina AI makes no warranty regarding the originality or intellectual property rights of AI-generated content and disclaims any liability for your use of such content.

8. Premium Features, Subscriptions, and Payments

8.1. Premium Tiers: Numina AI may offer various premium tiers or features that require payment. These may include enhanced UBPM insights, faster response times, increased tool usage, or other advanced functionalities. Details of these tiers, including pricing and features, will be provided within the Service or on our website.

8.2. Subscriptions: Access to certain premium features may be offered on a subscription basis. By subscribing, you agree to pay the applicable subscription fees and any taxes. Subscriptions will automatically renew unless canceled in accordance with the terms specified at the time of purchase.

8.3. Credits: Some features may operate on a credit-based system. You may purchase credits, which will be deducted based on your usage of specific features. Credits may have an expiration date, as specified at the time of purchase.

8.4. Payment: All payments are processed through secure third-party payment processors (e.g., Stripe). You agree to provide valid payment information and authorize us or our third-party payment processor to charge your chosen payment method for all applicable fees.

8.5. Refunds: All payments are generally non-refundable, except as required by law or as explicitly stated in our refund policy (if any) provided at the time of purchase.

8.6. Price Changes: We reserve the right to change our prices for premium features, subscriptions, or credits at any time. We will provide you with reasonable prior notice of any price changes.

9. Data Privacy and Collective Intelligence Consent

Your privacy is important to us. Our Privacy Policy (https://www.numinaai.com/privacy-policy) explains how we collect, use, store, and disclose your personal information. By using the Service, you consent to such collection, use, storage, and disclosure as described in the Privacy Policy.

Specifically, by using the Service, you acknowledge and consent to the potential collection and anonymization of your usage data for Collective Intelligence purposes. This means that anonymized and aggregated data from user patterns may be used to derive broader insights and improve the Service for all users, without identifying you personally. You will have options to manage your consent regarding data collection for collective intelligence as described in our Privacy Policy.

10. Disclaimers and Limitation of Liability

10.1. "AS IS" Basis: THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR COURSE OF PERFORMANCE.

10.2. No Guarantees: Numina AI does not warrant that the Service will be uninterrupted, secure, error-free, or free of viruses or other harmful components. We do not warrant that the results that may be obtained from the use of the Service will be accurate, reliable, or complete.

10.3. AI Limitations: You acknowledge that AI technologies are still evolving. The Service may produce inaccurate, incomplete, or offensive Content. You should not rely on AI-generated Content as factual or professional advice. Numina AI disclaims all liability for any reliance on or use of AI-generated Content.

10.4. Limitation of Liability: TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL NUMINA AI, ITS AFFILIATES, DIRECTORS, EMPLOYEES, AGENTS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO YOUR ACCESS TO OR USE OF, OR INABILITY TO ACCESS OR USE, THE SERVICE, EVEN IF NUMINA AI HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT SHALL NUMINA AI'S TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION EXCEED THE AMOUNT PAID BY YOU TO NUMINA AI FOR THE SERVICE IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR ONE HUNDRED U.S. DOLLARS ($100.00) IF YOU HAVE NOT HAD ANY PAYMENT OBLIGATIONS TO NUMINA AI, AS APPLICABLE.

11. Indemnification

You agree to indemnify, defend, and hold harmless Numina AI, its affiliates, officers, directors, employees, and agents from and against any and all claims, liabilities, damages, losses, costs, expenses, or fees (including reasonable attorneys' fees) that such parties may incur as a result of or arising from your (or anyone using your Account's) violation of these Terms or your use of the Service.

12. Termination

We may terminate or suspend your Account and access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach these Terms. Upon termination, your right to use the Service will immediately cease. If you wish to terminate your Account, you may simply discontinue using the Service or follow the Account termination process within the application.

13. Governing Law and Dispute Resolution

13.1. Governing Law: These Terms shall be governed by and construed in accordance with the laws of the State of California, USA, without regard to its conflict of law principles.

13.2. Arbitration: Any dispute, controversy, or claim arising out of or relating to these Terms or the Service shall be settled by binding arbitration administered by the American Arbitration Association (AAA) in accordance with its Commercial Arbitration Rules, and judgment on the award rendered by the arbitrator(s) may be entered in any court having jurisdiction thereof. The arbitration shall take place in San Francisco, California, USA.

13.3. Class Action Waiver: You agree that any arbitration or proceeding shall be limited to the dispute between us and you individually. To the full extent permitted by law, (i) no arbitration or proceeding shall be joined with any other; (ii) there is no right or authority for any dispute to be arbitrated on a class-action basis or to utilize class action procedures; and (iii) there is no right or authority for any dispute to be brought in a purported representative capacity on behalf of the general public or any other persons.

14. Miscellaneous

14.1. Entire Agreement: These Terms, together with our Privacy Policy, constitute the entire agreement between you and Numina AI regarding your use of the Service.

14.2. Severability: If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that these Terms will otherwise remain in full force and effect and enforceable.

14.3. Assignment: You may not assign or transfer these Terms, by operation of law or otherwise, without our prior written consent. Any attempt by you to assign or transfer these Terms, without such consent, will be null and void.

14.4. No Waiver: Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.

15. Contact Information

If you have any questions about these Terms, please contact us at:

Numina LLC
San Diego, California, USA
numinaworks@gmail.com`;

  return (
    <View style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={[
          styles.headerText,
          { color: isDarkMode ? '#ffffff' : '#000000' }
        ]}>
          Terms of Service
        </Text>
        <Text style={[
          styles.subHeaderText,
          { color: isDarkMode ? '#888888' : '#666666' }
        ]}>
          Please read and accept our terms to continue
        </Text>
      </View>

      {/* Scrollable Terms Content */}
      <View style={[
        styles.termsContainer,
        {
          backgroundColor: isDarkMode ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.02)',
          borderColor: isDarkMode ? '#333333' : '#e0e0e0',
        }
      ]}>
        <ScrollView
          ref={scrollViewRef}
          style={styles.scrollView}
          contentContainerStyle={styles.scrollContent}
          onScroll={handleScroll}
          scrollEventThrottle={16}
          showsVerticalScrollIndicator={true}
        >
          <Text style={[
            styles.termsText,
            { color: isDarkMode ? '#cccccc' : '#444444' }
          ]}>
            {termsContent}
          </Text>
        </ScrollView>
        
        {/* Scroll indicator */}
        {!hasScrolledToBottom && (
          <TouchableOpacity 
            style={styles.scrollIndicator}
            onPress={() => {
              scrollViewRef.current?.scrollToEnd({ animated: true });
            }}
            activeOpacity={0.8}
          >
            <BlurView 
              intensity={20} 
              tint={isDarkMode ? 'dark' : 'light'}
              style={styles.blurOverlay}
            />
            <View style={styles.scrollIndicatorContent}>
              <FontAwesome5 
                name="chevron-down" 
                size={16} 
                color={isDarkMode ? '#ffffff' : '#000000'} 
              />
              <Text style={[
                styles.scrollIndicatorText,
                { color: isDarkMode ? '#ffffff' : '#000000' }
              ]}>
                Tap to scroll to bottom
              </Text>
            </View>
          </TouchableOpacity>
        )}
      </View>

      {/* Acceptance Checkbox */}
      <View style={styles.checkboxContainer}>
        <Animated.View style={{ transform: [{ scale: checkboxScaleAnim }] }}>
          <TouchableOpacity
            style={[
              styles.checkbox,
              {
                backgroundColor: accepted 
                  ? (isDarkMode ? '#add5fa' : '#007AFF')
                  : 'transparent',
                borderColor: accepted 
                  ? (isDarkMode ? '#add5fa' : '#007AFF')
                  : (isDarkMode ? '#666666' : '#cccccc'),
              }
            ]}
            onPress={handleAcceptToggle}
            disabled={!hasScrolledToBottom}
          >
            {accepted && (
              <FontAwesome5 
                name="check" 
                size={12} 
                color={isDarkMode ? '#000000' : '#ffffff'} 
              />
            )}
          </TouchableOpacity>
        </Animated.View>
        
        <TouchableOpacity 
          style={styles.checkboxTextContainer}
          onPress={handleAcceptToggle}
          disabled={!hasScrolledToBottom}
        >
          <Text style={[
            styles.checkboxText,
            { 
              color: hasScrolledToBottom 
                ? (isDarkMode ? '#ffffff' : '#000000')
                : (isDarkMode ? '#666666' : '#999999')
            }
          ]}>
            I have read and agree to the Terms of Service
          </Text>
        </TouchableOpacity>
      </View>

      {/* Status indicator */}
      {!hasScrolledToBottom && (
        <Text style={[
          styles.statusText,
          { color: isDarkMode ? '#888888' : '#666666' }
        ]}>
          Please scroll through the entire document to continue
        </Text>
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  header: {
    marginBottom: 20,
    alignItems: 'center',
  },
  headerText: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 4,
    fontFamily: 'System', // Use system font to avoid font loading issues
  },
  subHeaderText: {
    fontSize: 14,
    fontWeight: '400',
    textAlign: 'center',
    fontFamily: 'System',
  },
  termsContainer: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    position: 'relative',
    marginBottom: 20,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  termsText: {
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '400',
    fontFamily: 'System',
  },
  scrollIndicator: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    overflow: 'hidden',
  },
  blurOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  scrollIndicatorContent: {
    padding: 12,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  scrollIndicatorText: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'System',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    gap: 12,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxTextContainer: {
  },
  checkboxText: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'System',
    textAlign: 'center',
  },
  statusText: {
    fontSize: 12,
    fontWeight: '400',
    textAlign: 'center',
    fontFamily: 'System',
  },
});